language: php
matrix:
  include:
    - php: 7.0
      before_script:
        - wget https://phar.phpunit.de/phpunit-6.4.phar
        - chmod +x phpunit-6.4.phar
        - wget https://phar.phpunit.de/phpunit-6.5.phar
        - chmod +x phpunit-6.5.phar
        - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      script:
        - ./phpunit-6.4.phar
        - ./phpunit-6.5.phar
env:
  - WP_VERSION=latest WP_MULTISITE=1
sudo: false
install:
  - composer install
before_deploy:
  - composer install --no-dev
  - bash bin/git-release.sh
deploy:
  provider: releases
  api_key:
    secure: jAk9v6tk8YaITI7r/gvwdwSzeZXBkI1O20Q2vdwdvaYjURIOtYym+gAmLmv4yk2RqUYKZ9RugfWNZxoAkrpL8frIPrix0v/mcBC1wFayNEuTOM2qK863Hp8v+IZk86j/QjLU4ZsQi2KB6+7MU2DWlGYsoHNQbMnMcA7C6C+lHJA=
  skip_cleanup: true
  file: multisite-language-switcher.zip
  on:
    repo: navigatrum/Multisite-Language-Switcher
    tags: true
